name: Build and deploy Node.js app to Azure Web App - onemillionaibackend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Delete old artifacts
        run: |
          OLD_ARTIFACTS=$(curl -sS --request GET \
            --url "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" \
            --header "Authorization: Bearer ${{ secrets.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 }}" \
            --header "Accept: application/vnd.github.v3+json" \
            | jq -r '.artifacts[].id')

          for ARTIFACT_ID in $OLD_ARTIFACTS; do
            curl --request DELETE \
              --url "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}" \
              --header "Authorization: Bearer ${{ secrets.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 }}" \
              --header "Accept: application/vnd.github.v3+json"
          done

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Install dependencies
        run: npm install --network-timeout=1000000

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Build and test
        run: npm run build --if-present

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'onemillionaibackend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C05C5CF16EC94B84AE8B264E1C8C6F41 }}
          package: .
